version: '3.8'

services:
  ctf-chmod-challenge:
    build: .
    ports:
      - "1337:1337"
    restart: unless-stopped
    container_name: ctf-chmod-challenge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"